### ISSUE TITLE
Different integrators

### ISSUE THREAD

**Issue by brendanjmeade** [brendanjmeade/Bem2d.jl#2]
Right now the only integrator that I've found to work is RK4().  There are many more to try in DifferentialEquations.jl.  It would be good to set up an example problem and then loop over a lot of integration methods with try/catch

**Comment by ChrisRackauckas** [comment]
Interesting. Is this something I should look into? That seems really peculiar. Even other explicit RKs are having issues?

**Comment by brendanjmeade** [comment]
I did a lot of experimenting last night and RK4 is the only solver I've had luck with.  I tried others in the RK family including VCABM5 but this eventually runs into an error as well.  I also tried Rosenbrock23 without success.  

Just include("ex_planarqdconst.jl") to see an example.   Right now it runs with RK4 but that can easily be edited on line 157.

 I'd really appreciate it you'd take a look at this!  Our ultimate goal is to integrate 100k+ plus of these ODEs.  Happy to chat and do anything I can to help!

**Comment by brendanjmeade** [comment]
> Interesting. Is this something I should look into? That seems really peculiar. Even other explicit RKs are having issues?

@ChrisRackauckas 

I’ve finally got a clean reproducible version of this issue :)

https://github.com/brendanjmeade/Bem2d.jl/blob/master/src/ex_integrate.jl

Here I’m integrating a small set of non-linear ODEs from earthquake physics.  As I mentioned before the RK4 integrator works well. VCABM5, DP5, and DP8 fail while iterating in the derivative calculating function “calc_dvθ”. They fail because they produce an intermediate value (named “vpara” in the “calc_dvθ”) that is negative.  This is a problem because the derivatives require the calculation of the log of this value (line 27).  This is what causes integrators other than RK4 to throw and error

The RK4 integrator type is set on line 122 of the file “ex_integrate.jl”.  If you run it with this one it’ll complete 1000 time steps happily. If this is changed to any of the other integration methods (just uncomment any of lines 123-125) the error that I described above is generated.

Any help/thoughts would be much appreciated!
