### ISSUE TITLE
examples/thrusttopo.jl referred to in README.md does not exist

### ISSUE THREAD

**Issue by ahbarnett** [brendanjmeade/Bem2d.jl#7]
it would be useful to see the code for the example. Or updating README.
Also, could you add other pictures of maybe more compilcated examples as PNG in the repo? Thanks, Alex

**Comment by brendanjmeade** [comment]
Thanks for pointing out that the README was out of date.  I've updated it now with a new figure that is produced by "faultboxgravitytopo.jl".  That's should be reproducible and the same script will also produce three other figures which don't look as good but are still useful.  I don't have any more complicated .png right now but they're pretty easy to build for some crazy cases.

**Comment by ahbarnett** [comment]
cool -thanks - now check your email! :)
